version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Ensure this environment variable is in your .env file
    volumes:
      - .:/app
    restart: always
